### ISSUE TITLE
README link is down

### ISSUE THREAD

**Issue by AloofBuddha** [cloud-annotations/object-detection-react#1]
The link https://cloud-annotations.github.io/training/ yields a 404. The css appears to be messed up too.

<img width="1440" alt="screen shot 2019-02-28 at 5 47 49 pm" src="https://user-images.githubusercontent.com/2440150/53603953-18899300-3b81-11e9-83fa-2d59fa224bdc.png">

**Comment by bourdakos1** [comment]
Thanks, fixed! Here's the proper link: https://github.com/cloud-annotations/training/
