### ISSUE TITLE
Unable to redefine video source

### ISSUE THREAD

**Issue by RickBadKan** [cloud-annotations/object-detection-react#10]
I wanted to change the video source from my camera to a Nest cam public link. I tried to change the source argument to a URL but it didn't work out. Does anyone know how to do this? I'm kind of new to React so any help would be nice.

**Comment by bourdakos1** [comment]
I haven’t used nest before, but I assume you would need to intercept a udp/rtp stream of some sort and pipe it to the browser as hls or mpeg dash. An easier approach might be to create a chrome extension that runs object detection on the actual nest website

**Comment by RickBadKan** [comment]
Yes, I can generate a public link (.m3u8) which can view the video stream. The thing is that I wanted to integrate this video to be processed natively by the code. Like the other branch you have, the stand alone video.

**Comment by bourdakos1** [comment]
Oh okay cool, I was actually working on a project last weekend that uses `.m3u8` I ended up using https://github.com/video-dev/hls.js/ I can try do upload the project here when I get a chance. Would you mind sharing the public link for testing purposes?

**Comment by RickBadKan** [comment]
It would be great if you could upload this project. I'd be very helpful.

About the public Nest link, I'd rather not share it for privacy reasons; it records my house 24/7. But there's a lot of free and public MPEG-DASH and HLS example test streams links, like [this one.](https://bitmovin.com/mpeg-dash-hls-examples-sample-streams/)

**Comment by bourdakos1** [comment]
Yea, of course, no problem :) I'll check those out and upload the code when I have something working

**Comment by RickBadKan** [comment]
@bourdakos1 any news on this code? I'd like to start using it with the Nest cam for some projects :)

**Comment by bourdakos1** [comment]
Oh sorry, yea I got something working but I forgot to upload the code. Do you mind re-opening this issue on the “training” repo?

**Comment by bourdakos1** [comment]
code available at https://github.com/cloud-annotations/object-detection-live-stream
