### ISSUE TITLE
Hello, I follow your steps, there are a few problems and I don't know how to solve them. Can you help me? 1. After the download is successful, I don't know where the model is downloaded. By default, success model files saved to bucket. ✨ Done. success Download complete. I downloaded a model-55rb2kkf tarball, but can't find model-web after decompression. Then copy the model_web directory generated from the object detection walkthrough And paste it into the public folder of this repo. This sentence did not understand, public, repo this is where?

### ISSUE THREAD

**Issue by Jimmy501C** [cloud-annotations/object-detection-react#11]
Hello, I follow your steps, there are a few problems and I don't know how to solve them. Can you help me? 1. After the download is successful, I don't know where the model is downloaded. By default, success model files saved to bucket. ✨ Done. success Download complete. I downloaded a model-55rb2kkf tarball, but can't find model-web after decompression. Then copy the model_web directory generated from the object detection walkthrough And paste it into the public folder of this repo. This sentence did not understand, public, repo this is where?

**Comment by bourdakos1** [comment]
There was no `model-web` in the `model-55rb2kkf` folder? Were there any other files?
