### ISSUE TITLE
How to verify the working of model ?

### ISSUE THREAD

**Issue by SandeshKa07** [cloud-annotations/object-detection-react#12]
So after following the training link, i downloaded the model using "cacli download". The model downloaded was model-wnk7jbo1. Copied the entire folder to public folder of the repository.

After copying public repo looks something like this
![tree](https://user-images.githubusercontent.com/6094417/62996562-68c18c80-be65-11e9-84d5-6382b144ebb6.png).

Going forward i started the application using npm start, it was a clean start and gave the following message
`Compiled successfully!
You can now view tensorflowjs-object-detection in the browser.
  Local:            http://localhost:3000/
  On Your Network:  http://192.168.0.5:3000/
Note that the development build is not optimized.
To create a production build, use yarn build.`

But if i open the application using browser by following the link, its just camera output i can see. How to verify the working of mode ?
since in my case it is not detecting the objects i trained.

**Comment by bourdakos1** [comment]
Looks like the model never trained, you should see a `model_web` folder in there if it did

**Comment by bourdakos1** [comment]
run `cacli list` to see if the model failed to train or is still running/pending

**Comment by SandeshKa07** [comment]
This is the status. It says status is completed. However, after downloading the model, i couldn't see **model_web** directory. 
![cacli_model](https://user-images.githubusercontent.com/6094417/63122385-eb059a00-bfa6-11e9-8810-4bffbc988720.png)

**Comment by bourdakos1** [comment]
what is inside `model-zyn0x1f1`?

**Comment by ptchau2003** [comment]
> Looks like the model never trained, you should see a `model_web` folder in there if it did

Same issue for me, I tried train several models but I can't find the model_web.

![image](https://user-images.githubusercontent.com/54661468/63919235-03fe5880-ca47-11e9-91c7-5250cf2c92e8.png)

![image](https://user-images.githubusercontent.com/54661468/63919298-23958100-ca47-11e9-972f-11f838c9bb9d.png)

![image](https://user-images.githubusercontent.com/54661468/63919368-4b84e480-ca47-11e9-96c7-fe6838c2e629.png)

![image](https://user-images.githubusercontent.com/54661468/63919679-e7aeeb80-ca47-11e9-8312-24350d1fc7b8.png)

**Comment by bourdakos1** [comment]
I just fixed this issue yesterday, you’ll need to update cacli and retrain the model
