### ISSUE TITLE
How to do this with a single .jpeg file?

### ISSUE THREAD

**Issue by Arykelton** [cloud-annotations/object-detection-react#13]
Hello friend, this may be a dumb question, but how do you make this code work by pointing to just one image instead of a webcam stream? I would just like to detect objects in just one image but I couldn't and I didn't find an easy way to do it on the internet, but I believe it is possible to do it in an easy way. Could you give me a hand?

I tried to modify useWebcam to capture only one frame but I was unsuccessful.

**Comment by bourdakos1** [comment]
I cant give a detailed answer at the moment, but check out the sdk it has some instructions on how to use object detection with image tags https://github.com/cloud-annotations/object-detection-js

I can be more helpful in a couple days
