### ISSUE TITLE
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Arykelton** [cloud-annotations/object-detection-react#14]
I am getting the error requesting omodel.json, the server starts up correctly, the camera works, the problem starts when trying to retrieve the model, the program seems to be getting index.html from the public folder.

Considerations:
Model_web is in the public folder and was converted correctly
The model.json contains no errors, already checked

**Comment by bourdakos1** [comment]
That normally means that the file isn't being served properly. Make sure you’re loading the page at localhost:3000 and not just the index.html file

**Comment by Arykelton** [comment]
yes I am starting the server and accessing from localhost

**Comment by bourdakos1** [comment]
Have you made any changes to the code?

**Comment by Arykelton** [comment]
no, I'm just using what I got from git clone

**Comment by bourdakos1** [comment]
I'm not sure then... I've only seen that error if the model wasn't there or not accessing it from the local server

**Comment by bourdakos1** [comment]
can you send a screenshot of the project structure and maybe upload a zip of the model_web folder?

**Comment by Arykelton** [comment]
Of course, thank for suport
I removed node modules for this answer to be clear, but they are present in my folder.

[model.json zip (on google drive, file is 50mb)](https://drive.google.com/file/d/1TV2CZfUOHCft9yp57mrMtnCNfZKIc64F/view?usp=sharing)
.
├── LICENSE
├── node_modules
├── package.json
├── package-lock.json
├── public
│   ├── index.html
│   └── model_web
│       ├── group1-shard10of13.bin
│       ├── group1-shard11of13.bin
│       ├── group1-shard12of13.bin
│       ├── group1-shard13of13.bin
│       ├── group1-shard1of13.bin
│       ├── group1-shard2of13.bin
│       ├── group1-shard3of13.bin
│       ├── group1-shard4of13.bin
│       ├── group1-shard5of13.bin
│       ├── group1-shard6of13.bin
│       ├── group1-shard7of13.bin
│       ├── group1-shard8of13.bin
│       ├── group1-shard9of13.bin
│       └── model.json
├── README.md
├── src
│   ├── index.js
│   ├── styles.module.css
│   ├── useBoxRenderer.js
│   ├── useModel.js
│   └── useWebcam.js
└── yarn.lock

**Comment by bourdakos1** [comment]
Did you label and train this with Cloud Annotations?

**Comment by bourdakos1** [comment]
The error is that there is no `labels.json` file, but even if you add one your model has TensorFlow ops that aren't supported

**Comment by Arykelton** [comment]
Not the training, I used a template I had created and converted using your tutorial. Do you think this could be it? Is the generated JSON not compatible with code?

The correct solution then would be for me to redo the training and model using Cloud Annotations, correct?

**Comment by bourdakos1** [comment]
Yea, that would definitely solve it, but it's not 100% necessary

**Comment by bourdakos1** [comment]
Here's the training code, there's a bit of post processing that goes on to remove certain op https://github.com/cloud-annotations/training/releases/download/v1.2.0/training.zip

**Comment by bourdakos1** [comment]
I'm gonna close this issue :) Feel free to reopen if it doesn't work after training with Cloud Annotations
