### ISSUE TITLE
How to Transfer to Raspberry Pi?

### ISSUE THREAD

**Issue by adelaarenas** [cloud-annotations/object-detection-react#19]
is it possible to transfer the codes and the model to rpi? need help. can u please help me by giving brief steps?

**Comment by bourdakos1** [comment]
You can `scp` all the files to the raspberry pi following these steps: https://www.raspberrypi.org/documentation/remote-access/ssh/scp.md

An alternate:
You could clone the repo directly to the raspberry pi using `git` and you could download the model to the raspberry pi by installing `cacli` and running `cacli download MODEL-ID`

Hope this helps :)

**Comment by adelaarenas** [comment]
Omg. Truly grateful! I will do. I already cloned the repo and downloaded
the model to raspberry pi but forgot to do the cacli part. Thank you very
much!!

**Comment by adelaarenas** [comment]
How do we install cacli on raspberry pi sir? 😰

**Comment by bourdakos1** [comment]
Are you able to run this script:
```
curl -sSL https://cloud.annotations.ai/install.sh | sudo sh
```

**Comment by adelaarenas** [comment]
Yes, but it didnt work 😥 I’m working on raspberry pi 3

**Comment by bourdakos1** [comment]
I haven’t tested on a raspberry pi yet, I can try tomorrow morning. Someone else just mentioned the install script isn’t working though, so I’ll double check that now

**Comment by adelaarenas** [comment]
Thank you! ❤️

**Comment by bourdakos1** [comment]
@moficodes do you mind testing this on a raspberry pi if you have on handy? or some sort of linux?

**Comment by moficodes** [comment]
Dont have a pi setup. But can try to check on a virtual machine running a raspbian flavor. 
in the mean time @adlarenas any specific error you got with the script?

**Comment by bourdakos1** [comment]
@adlarenas do you mind running:
```
uname
```

and:
```
uname -m
```

and post the results here?

**Comment by adelaarenas** [comment]
Here are the results:

pi@raspberrypi:~ $ uname
Linux
pi@raspberrypi:~ $ uname -m
armv7l
pi@raspberrypi:~ $

Actually, when i re-run the very first commqnd you sent me, I was able to
install cacli ❤️. Then after I entered my credentials and all for the
download, I ran the command npm start and below is the result:

> tensorflowjs-object-detection@1.0.0 start
/home/pi/Downloads/object-detection-react-master
> react-scripts start

sh: 1: react-scripts: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! tensorflowjs-object-detection@1.0.0 start: `react-scripts start`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the tensorflowjs-object-detection@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean
to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-01-30T08_58_56_504Z-debug.log

**Comment by bourdakos1** [comment]
@adlarenas Ah that's good to hear, I made changes to the install script last night, so I guess that fixed it :)

You just need to run:
```
npm install
```

before running:
```
npm start
```

**Comment by adelaarenas** [comment]
Yay! Success! Thank you! ❤️

**Comment by bourdakos1** [comment]
yay! no problem :)
