### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'dataSync' of undefined

### ISSUE THREAD

**Issue by Arykelton** [cloud-annotations/object-detection-react#2]
I trained my model, however I got the following error, the camera opens and shows some frames until it stops and the message appears:
Unhandled Rejection (TypeError): Can not read property 'dataSync' of undefined

The error comes from line 73 of index.js:
const scores = result [1] .dataSync ()

Convert "result" to string on console and get:
Tensor
     [[[0.9944437, 0.0055564],
       [0.9986057, 0.0013941],
       [0.9995164, 0.0004835],
       ...,
       [0.9984756, 0.0015245],
       [0.9997611, 0.0002387],
       [0.9883699, 0.0116299]]]

EDIT 1: Convert result[1] to string and get:
undefined

**Comment by bourdakos1** [comment]
uh sorry I just saw this, what version of cacli did you use to train the model? If this was trained pre-cacli I think thats the problem, you might need to retrain the model
