### ISSUE TITLE
Could not open ObjectDetectionVideo.js in the editor.

### ISSUE THREAD

**Issue by dryptm** [cloud-annotations/object-detection-react#28]
The react app is not able to load on the localhost:3000 in the chromium based browsers like Google Chrome or Edge but it is working fine on Firefox.

#### The issues below come after including my personal model. So the model is not undefined.

Issue that it says on the browser, it says :
`Unhandled Rejection (TypeError): Cannot read property 'detect' of undefined`
and on the console, it says:
`Could not open ObjectDetectionVideo.js in the editor.`
![image](https://user-images.githubusercontent.com/42112297/99976575-9e278a80-2dc9-11eb-83f7-648472c2f6ea.png)

![image](https://user-images.githubusercontent.com/42112297/99976651-bd261c80-2dc9-11eb-99ff-6d91a8a8b1e6.png)

**Comment by bourdakos1** [comment]
That normally means the model is a classification model and not an object detection model

**Comment by bourdakos1** [comment]
oh it works in firefox? like you are getting detections?

**Comment by dryptm** [comment]
> oh it works in firefox? like you are getting detections?

Yes, it is working in firefox 
I am getting detections

**Comment by bourdakos1** [comment]
Interesting, do you mind sharing your model so I can try and debug in chrome?

**Comment by dryptm** [comment]
> Interesting, do you mind sharing your model so I can try and debug in chrome?

no problem...
you will get the model in the public folder of this project, the link is down below...
https://github.com/dryptm/Pothole_detection-System
don't clone my project to be on the safer side, rather use this model in the actual object-detection-react project.

**Comment by dryptm** [comment]
> That normally means the model is a classification model and not an object detection model

but this react app is for object detection, not for classification. so why does it show the classification errors!?

**Comment by bourdakos1** [comment]
I’m not sure I understand the question

**Comment by dryptm** [comment]
> I’m not sure I understand the question

its okay, skip the question...
by the way, did you debug the code !?

**Comment by bourdakos1** [comment]
I haven’t had a chance yet

**Comment by dryptm** [comment]
> I haven’t had a chance yet

Ooh...

**Comment by dryptm** [comment]
if you build the project and then run it, it runs fine on every browser!!!

**Comment by bourdakos1** [comment]
Thanks for the update :)

**Comment by ykoyfman** [comment]
@dryptm I'm running into this as well (on Android mobile Chrome) - can you elaborate on what your solution was?

**Comment by dryptm** [comment]
> @dryptm I'm running into this as well (on Android mobile Chrome) - can you elaborate on what your solution was?

just build the app and it will take care of all the files itself!

**Comment by ykoyfman** [comment]
Looks like I can only get things working in Chrome/Android when I use the forward facing camera (which is the default.) When I tried switching the webcam to the 'environment' facingMode, that's when I started hitting these errors.

**Comment by bourdakos1** [comment]
@ykoyfman this is probably causing that issue: https://github.com/cloud-annotations/object-detection-react/blob/f3f4a902a63a8f6aee57be12529dc05c19dffcb0/src/object-detection-video/useWebcam.js#L10

**Comment by dryptm** [comment]
> Looks like I can only get things working in Chrome/Android when I use the forward facing camera (which is the default.) When I tried switching the webcam to the 'environment' facingMode, that's when I started hitting these errors.

I myself don't know how to switch the cameras in the respective devices....... so I am very sorry but I can not help with this
