### ISSUE TITLE
Run TensorFlow Node JS

### ISSUE THREAD

**Issue by wilkensgomes** [cloud-annotations/object-detection-react#35]
How do I run the converted model with the js tensorflow for node?

Any example to receive only boxes and scores?

**Comment by bourdakos1** [comment]
You can use the javascript sdk: https://github.com/cloud-annotations/javascript-sdk

Just make sure you install `@cloud-annotations/models-node` not `@cloud-annotations/models`

**Comment by wilkensgomes** [comment]
`const models = require('@cloud-annotations/models-node')
const fs = require('fs');


async function detect() {
    const imageFile = fs.readFileSync('image.jpg')
    models.load('file://model_web').then(async (model) => {
        const predictions = await model.detect(imageFile);
        console.log(predictions);
    })
}`

**I get this error when trying to run the above code:**
**ENVIRONMENT:** WINDOWS 10, NODE v15.7.0

 internal/modules/cjs/loader.js:1122
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.

**Comment by bourdakos1** [comment]
maybe try `npm rebuild @cloud-annotations/models-node --build-from-source`

**Comment by wilkensgomes** [comment]
The same error continues. ☹

![Captura de tela 2021-01-26 142742](https://user-images.githubusercontent.com/38788876/105881267-0b7eb400-5fe3-11eb-89d1-3f14c1a90abd.png)

**Comment by bourdakos1** [comment]
oh what is `file://model_web` try without `file://`

**Comment by wilkensgomes** [comment]
disregard `file://` even removed does not work!

**Comment by wilkensgomes** [comment]
`Error: The specified module could not be found.
\\?\D:\TFJS\node_modules\@tensorflow\tfjs-node\lib\napi-v6\tfjs_binding.node`

**Solution:** move `D:\ProjectPath\node_modules\@tensorflow\tfjs-node\deps\lib\tensorflow.dll` to `D:\ProjectPath\node_modules\@tensorflow\tfjs-node\lib\napi-v6\`

**Comment by bourdakos1** [comment]
@johnwalicki is this the issue that you were having as well?
