### ISSUE TITLE
How to use detection for static images by uploading them?

### ISSUE THREAD

**Issue by NSTiwari** [cloud-annotations/object-detection-react#37]
The app is great in real-time. How can it be tweaked to detect objects in static images uploaded by the user?

**Comment by bourdakos1** [comment]
Thanks :) 

Check out the SDK there are instructions on how to use it: https://github.com/cloud-annotations/javascript-sdk

**Comment by brony28** [comment]
Hello @bourdakos1 , I tried using the SDK and it's showing the proper result in browser's Console Panel. But there is no bounding box appearing on the detected object.

**Comment by bourdakos1** [comment]
Ah, yea you would need to draw the bounding boxes yourself somehow. I normally use a `<canvas>` element which has `strokeRect` as part of its API: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/strokeRect

**Comment by brony28** [comment]
Oh Yes. It worked. Thank you, Sir.
