### ISSUE TITLE
App Page Doesn't Show

### ISSUE THREAD

**Issue by bnornholm** [cloud-annotations/object-detection-react#6]
After copying over the model_web and starting the app, the webpage doesn't show anything.

**Comment by bourdakos1** [comment]
Does it ask for webcam permissions?

**Comment by bnornholm** [comment]
It did not.  Let me reset the cache/cookies and try again. Is a webcam required for the app to work?

I was looking to try it as a screen scraping tool to identify objects.

**Comment by bourdakos1** [comment]
the webcam is required for this particular demo, but you could modify the code to change it to just run via a link/uploaded file
