### ISSUE TITLE
Bug fix

### ISSUE THREAD

**Issue by oumingyang** [cloud-annotations/object-detection-react#8]
Hi，There is an error after I run the App
**Error: The model does not contain control flow or dynamic shape ops, please use execute method for better performance.**
I fixed it refer to a similar[ issue ](https://github.com/tensorflow/tfjs/issues/1169)
I hope it would be helpful for somebody.

**Comment by bourdakos1** [comment]
You are using the wrong model type (classification) this app only works with object detection
